### ISSUE TITLE
Create a simple gallery section for listing organizers on the about page

### ISSUE THREAD

**Issue by machow** [socialjusticehackathon/website#6]
Sections like [Organizers on the About page](https://socialjusticehackathon.github.io/website/about.html) contain of a gallery of people. Each item is a photo, along with a description.

This issue is to track generating sections like this by...

* Committing organizer data to the repo (e.g. organizers.csv, exported from a spreadsheet).
  - I've added an [about--organizers spreadsheet](https://docs.google.com/spreadsheets/d/1sBa7j4rwgNr0EFLa4sZ_8EugCDlmCxtRaMvTlOs_U-E/edit?usp=sharing) to the website folder on google drive
  - (Here is last year's [google doc](https://docs.google.com/document/d/1-n6zXTi285g1DTA9MHKsuffaHpEv_r6voqrR66sbqTg/edit?usp=sharing))
* Committing organizer photos to the repo.
* Generating a section using either code or a custom quarto gallery

## Option 1: using code

This approach is used in the [quartodoc example page](https://machow.github.io/quartodoc/examples/) ([source code](https://github.com/machow/quartodoc/blob/main/docs/examples/index.qmd))

With this approach, you just write a qmd with a code block that returns output "asis":

``````
```{python}
#| output: asis
#| echo: false

# this is a print statement, but imaging you used a loop to generate a card
# for each person, etc..
print("""
::: {.some-div}
:::
""")
```
``````

## Option 2: using a gallery with an ejs template

See the [Custom Listings page](https://quarto.org/docs/websites/website-listings-custom.html) on quarto.org. This is used in [quarto's website gallery](https://quarto.org/docs/gallery/) ([source code](https://github.com/quarto-dev/quarto-web/tree/main/docs/gallery)) and the [shiny gallery](https://shiny.posit.co/py/gallery/) ([source code](https://github.com/posit-dev/py-shiny-site/tree/main/gallery)) 

## Option 3: bail out and do it manually

We can always code it manually, but I suspect other parts of the site will benefit from this kind of workflow, so seems nice for us to get a feel for it!

**Comment by ha0ye** [comment]
To me, some of the key questions are:
1. How frequently will the data / images be updated?
2. How custom of a styling do we want?
3. How do we want to store image content? A CSV of the names (or code to pull from google sheets) is fine, but I wouldn't want to depend on external images to persist for a website.

**Comment by machow** [comment]
Let's plan to create an organizers folder, with a index.qmd file, and all the assets for generating items (e.g. a csv of organizer info, all of the images). Once we have the code and style locked down, we can always shift it somewhere else on the site.

**Comment by insiyahj** [comment]
> To me, some of the key questions are:
> 
> 1. How frequently will the data / images be updated?
> 
> 2. How custom of a styling do we want?
> 
> 3. How do we want to store image content? A CSV of the names (or code to pull from google sheets) is fine, but I wouldn't want to depend on external images to persist for a website.

I don't expect changes to be as often if we get people's input/approval via a google doc/shared file prior to pushing to the web.

We'll need to add new profiles when we have a new organizer join which may be a few a month, and then redo the list with the next iteration of the hackathon every year or so.
